version: 2
formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: doc/requirements.txt

sphinx:
  builder: html
  configuration: doc/sphinx/conf.py
