sudo: enabled
language: c++

matrix:
    - os: linux
      compiler:
            - gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - TO_TEST=BINDINGS

    - os: linux
      compiler:
            - gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - TO_TEST=BINDINGS

    - os: linux
      compiler:
            - gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - TO_TEST=BINDINGS

before_install:
      - eval "$(MATRIX_EVAL)"
      - echo "$TO_TEST"
      - if [ "$TO_TEST" = "BINDINGS" ]; then sudo apt-get install -y build-essential cmake libboost-dev libblas-dev liblapack-dev python3-dev python3-networkx python3-numpy python3-scipy python3-matplotlib python3-nose; fi
install:
      - eval "$(MATRIX_EVAL)"
      - if [ "$TO_TEST" = "BINDINGS" ]; then cmake -DPYTHON_EXECUTABLE=$(python-config --prefix)/bin/python3.5 -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython3.5.so -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python3.5 -D WRAP_PYTHON=ON -D BUILD_UTILS=ON .; fi
      - make -j 2
script:
      - if [ "$TO_TEST" = "BINDINGS" ]; then nosetests3; fi
      - test/drivers/test_drivers.sh
