sudo: enabled
before_install:
      - sudo apt-get install -y build-essential cmake libboost-dev libblas-dev liblapack-dev python-dev python-networkx python-numpy python-scipy python-matplotlib python-nose
install:
      - cmake -D WRAP_PYTHON=ON .
      - make
script:
      - nosetests
