name: Make test packages

on: pull_request

jobs:
      deploy_linux_test:
            runs-on: ubuntu-latest
            container: quay.io/pypa/manylinux2014_x86_64
            steps:
            - uses: actions/checkout@v2
              with:
                    path: neml
            - name: Install dependencies
              run: |
                    yum -y install cmake blas-devel lapack-devel zlib-devel
            - name: Build sdist
              run: |
                    cd $GITHUB_WORKSPACE/neml
                    /opt/python/cp38-cp38/bin/python setup.py sdist --dist-dir=$GITHUB_WORKSPACE/source_packages
            - name: Build manylinux wheel on each version
              run: |
                    for PYTHON in /opt/python/*/bin/; do
                        $PYTHON/pip install -r $GITHUB_WORKSPACE/neml/requirements.txt
                        $PYTHON/pip wheel $GITHUB_WORKSPACE/neml/ --no-deps -w $GITHUB_WORKSPACE/original_binary_packages
                    done
            - name: Fix packages with auditwheel
              run: | 
                    for whl in $GITHUB_WORKSPACE/original_binary_packages/*.whl; do
                        auditwheel repair $whl --plat manylinux2014_x86_64 -w $GITHUB_WORKSPACE/binary_packages
                    done
            - name: Test each binary package
              run: |
                    cd $HOME
                    for PYTHON in /opt/python/*/bin/; do
                        $PYTHON/pip install neml --no-index -f $GITHUB_WORKSPACE/binary_packages
                        $PYTHON/nosetests $GITHUB_WORKSPACE/neml/test/
                    done
            - name: Move packages to the standard location
              run: |
                    cd $GITHUB_WORKSPACE/neml
                    mkdir -p dist
                    cp $GITHUB_WORKSPACE/source_packages/* dist
                    cp $GITHUB_WORKSPACE/binary_packages/* dist
            - name: Upload the packages to PyPi test
              uses: pypa/gh-action-pypi-publish@master
              with:
                    password: ${{ secrets.PIPY_TEST_PASSWORD }}
                    repository_url: https://test.pypi.org/legacy/
