name: Make test packages

on: pull_request

jobs:
      build_wheels_mac_linux:
            env:
                  CIBW_SKIP: cp27-* cp35-*
                  CIBW_BEFORE_ALL_LINUX: yum -y install cmake blas-devel lapack-devel
                  CIBW_BEFORE_ALL_MACOS: brew install cmake openblas superlu gfortran
                  CIBW_BEFORE_BUILD: pip install -r requirements.txt
                  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
                  CIBW_MANYLINUX_I686_IMAGE: manylinux2014
                  CIBW_TEST_REQUIRES: nose
                  CIBW_TEST_COMMAND: nosetests {project}/test
            name: Build wheels on ${{ matrix.os }}
            runs-on: ${{ matrix.os }}
            strategy:
                  matrix:
                        os: [ubuntu-latest, macos-latest]
            steps:
                  - uses: actions/checkout@v2
                  - uses: actions/setup-python@v2
                    with:
                          python-version: '3.8'
                  - name: Install cibuildwheel
                    run: python -m pip install cibuildwheel
                  - name: Build wheels
                    run: python -m cibuildwheel --output-dir wheelhouse
                  - uses: actions/upload-artifact@v2
                    with:
                          path: ./wheelhouse/*.whl
      build_wheels_windows:
            strategy:
                  matrix:
                        python-version: [3.6,3.7,3.8,3.9]
            name: Build wheels on windows-latest, python ${{ matrix.python-version }}
            runs-on: windows-latest
            defaults:
                  run:
                        shell: msys2 {0}
            steps:
                  - uses: msys2/setup-msys2@v2
                    with:
                          msystem: MINGW64
                          update: true
                          install: git mingw-w64-x86_64-toolchain base-devel mingw-w64-x86_64-openblas mingw-w64-x86_64-cmake
                  - uses: actions/setup-python@v2
                    with:
                          python-version: ${{ matrix.python-version }}
                  - name: Install pip
                    run: |
                          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
                          python get-pip.py
                  - uses: actions/checkout@v2
                  - name: Setup for build
                    run: pip install -r requirements.txt
                  - name: Build wheel
                    run: pip wheel . --no-deps
      build_sdist:
            name: Build source distribution
            runs-on: ubuntu-latest
            steps:
                  - uses: actions/checkout@v2
                  - uses: actions/setup-python@v2
                    name: Install Python
                    with:
                          python-version: '3.8'
                  - name: Build source distribution
                    run: python setup.py sdist
                  - uses: actions/upload-artifact@v2
                    with:
                          path: dist/*.tar.gz

