name: test-bindings
on: [push, pullrequest]
jobs:
      test-gcc-7:
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v2
            - run: sudo apt install build-essential cmake libblas-dev liblapack-dev python3-dev python3-networkx python3-numpy python3-scipy python3-matplotlib python3-nose
            - run: cmake -DPYTHON_EXECUTABLE=$(python-config --prefix)/bin/python3.5 -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython3.5.so -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python3.5 -D WRAP_PYTHON=ON
            - run: make -j 2
            - run: nosetests3
