name: tests
on: [push, pull_request]
jobs:
      test-bindings-linux:
            runs-on: ubuntu-latest
            strategy:
                  matrix:
                        btype: [Release, Debug]
            steps:
            - uses: actions/checkout@v2
              with:
                    submodules: recursive
            - run: sudo apt update
            - run: sudo apt install build-essential cmake libblas-dev liblapack-dev python3-dev python3-networkx python3-numpy python3-scipy python3-matplotlib python3-nose
            - run: cmake -D CMAKE_BUILD_TYPE=${{ matrix.btype }} -D WRAP_PYTHON=ON .
            - run: make -j 2
            - run: nosetests3 -v 
      test-base-linux:
            runs-on: ubuntu-latest
            strategy:
                  matrix:
                        btype: [Release, Debug]
            steps:
            - uses: actions/checkout@v2
              with:
                    submodules: recursive
            - run: sudo apt update
            - run: sudo apt install build-essential cmake libblas-dev liblapack-dev
            - run: cmake -D CMAKE_BUILD_TYPE=${{ matrix.btype }} -D BUILD_UTILS=ON .
            - run: make -j 2
            - run: test/drivers/test_drivers.sh
      test-bindings-mac:
            runs-on: macos-latest
            strategy:
                  matrix:
                        btype: [Release, Debug]
            steps:
            - uses: actions/checkout@v2
              with:
                    submodules: recursive
            - run: brew update
            - run: brew install cmake openblas superlu python 1>/dev/null || true
            - run: pip3 install --user networkx numpy scipy matplotlib nose
            - run: cmake -D CMAKE_BUILD_TYPE=${{ matrix.btype }} -D WRAP_PYTHON=ON -D PYTHON_EXECUTABLE=$(python3-config --prefix)/bin/python3.9 -D PYTHON_LIBRARY=$(python3-config --prefix)/lib/libpython3.9.dylib -D PYTHON_INCLUDE_DIR=$(python3-config --prefix)/include/python3.9 -D USE_OPENMP=OFF .
            - run: make -j 2
            - run: ~/Library/Python/3.9/bin/nosetests -v
      test-base-mac:
            runs-on: macos-latest
            strategy:
                  matrix:
                        btype: [Release, Debug]
            steps:
            - uses: actions/checkout@v2
              with:
                    submodules: recursive
            - run: brew update
            - run: brew install cmake openblas superlu gfortran 1>/dev/null || true
            - run: brew reinstall gcc
            - run: cmake -D CMAKE_CXX_COMPILER=/usr/bin/g++ -D CMAKE_C_COMPILER=/usr/bin/gcc -D CMAKE_Fortran_COMPILER=/usr/local/bin/gfortran -D CMAKE_BUILD_TYPE=${{ matrix.btype }} -D USE_OPENMP=OFF -D BUILD_UTILS=ON .
            - run: make -j 2
            - run: test/drivers/test_drivers.sh
      test-bindings-windows:
           runs-on: windows-latest
           strategy:
             matrix:
               btype: [Release, Debug]
           defaults:
             run:
               shell: msys2 {0}
           steps:
           - uses: actions/checkout@v2
             with:
                   submodules: recursive
           - uses: msys2/setup-msys2@v2
             with:
               msystem: MINGW64
               update: true
               install: git mingw-w64-x86_64-toolchain base-devel mingw-w64-x86_64-openblas mingw-w64-x86_64-cmake mingw-w64-x86_64-python-pip mingw-w64-x86_64-python-numpy mingw-w64-x86_64-python-scipy mingw-w64-x86_64-python-networkx mingw-w64-x86_64-python-matplotlib
           - run: pip install nose
           - run: cmake . -G"MSYS Makefiles" -D"WRAP_PYTHON=ON" -D"CMAKE_BUILD_TYPE=${{ matrix.btype }}"
           - run: make -j 2
           - run: nosetests -v --ignore-files="test_hucocks.py"
      test-base-windows:
           runs-on: windows-latest
           strategy:
             matrix:
               btype: [Release, Debug]
           defaults:
             run:
               shell: msys2 {0}
           steps:
           - uses: actions/checkout@v2
             with:
                   submodules: recursive
           - uses: msys2/setup-msys2@v2
             with:
               msystem: MINGW64
               update: true
               install: git mingw-w64-x86_64-toolchain base-devel mingw-w64-x86_64-openblas mingw-w64-x86_64-cmake
           - run: cmake . -G"MSYS Makefiles" -D"BUILD_UTILS=ON" -D"CMAKE_BUILD_TYPE=${{ matrix.btype }}"
           - run: make -j 2
           - run: PATH=$PATH:$PWD/lib ./test/drivers/test_drivers.sh
