name: tests-pass
on: [push, pull_request]
jobs:
      test-bindings:
            runs-on: ubuntu-latest
            strategy:
                  matrix:
                        btype: [Release, Debug]
            steps:
            - uses: actions/checkout@v2
            - run: python --version
            - run: sudo apt install build-essential cmake libblas-dev liblapack-dev python3-dev python3-networkx python3-numpy python3-scipy python3-matplotlib python3-nose
            - run: cmake -D CMAKE_BUILD_TYPE ${{ matrix.btype }} -D WRAP_PYTHON=ON .
            - run: make -j 2
            - run: nosetests3
